_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 9
                - 55
                - 77
                - 103
            "2":
                - 1
                - 9
                - 55
                - 77
                - 103
            "3":
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
